# Generated by Django 2.0.4 on 2018-05-01 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_event_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='status',
            new_name='is_completed',
        ),
    ]
