# Generated by Django 2.0.4 on 2018-05-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0006_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
