# Generated by Django 2.0.4 on 2018-05-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0007_auto_20180507_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('M', 'Menu'), ('T', 'Task'), ('P', 'Payment'), ('B', 'Birthday'), ('R', 'Reminder')], max_length=1),
        ),
    ]
