# Generated by Django 2.0.4 on 2018-04-18 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('key', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=25)),
                ('points_total', models.IntegerField()),
                ('points_mensual', models.IntegerField()),
                ('allocation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SharedDoorsAPP.Flat')),
            ],
        ),
    ]
