# Generated by Django 2.0.4 on 2018-04-18 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SharedDoorsAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField(null=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharedDoorsAPP.Flat')),
            ],
        ),
        migrations.CreateModel(
            name='EventUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharedDoorsAPP.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharedDoorsAPP.User')),
            ],
        ),
    ]
